<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Kotest" tests="2" skipped="0" failures="0" errors="2" time="5.439" hostname="849f2855b6ce" timestamp="2020-03-31T13:12:50">
<properties>
<property name="file.encoding" value="UTF-8"/>
<property name="file.separator" value="/"/>
<property name="java.class.path" value="end-to-end-tests-0.1.0.jar"/>
<property name="java.class.version" value="57.0"/>
<property name="java.home" value="/usr/java/openjdk-13"/>
<property name="java.io.tmpdir" value="/tmp"/>
<property name="java.library.path" value="/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"/>
<property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
<property name="java.runtime.version" value="13.0.1+9"/>
<property name="java.security.auth.login.config" value="gss.conf"/>
<property name="java.specification.name" value="Java Platform API Specification"/>
<property name="java.specification.vendor" value="Oracle Corporation"/>
<property name="java.specification.version" value="13"/>
<property name="java.vendor" value="Oracle Corporation"/>
<property name="java.vendor.url" value="https://java.oracle.com/"/>
<property name="java.vendor.url.bug" value="https://bugreport.java.com/bugreport/"/>
<property name="java.version" value="13.0.1"/>
<property name="java.version.date" value="2019-10-15"/>
<property name="java.vm.compressedOopsMode" value="32-bit"/>
<property name="java.vm.info" value="mixed mode, sharing"/>
<property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
<property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
<property name="java.vm.specification.vendor" value="Oracle Corporation"/>
<property name="java.vm.specification.version" value="13"/>
<property name="java.vm.vendor" value="Oracle Corporation"/>
<property name="java.vm.version" value="13.0.1+9"/>
<property name="javax.security.auth.useSubjectCredsOnly" value="false"/>
<property name="jdk.debug" value="release"/>
<property name="line.separator" value="
"/>
<property name="os.arch" value="amd64"/>
<property name="os.name" value="Linux"/>
<property name="os.version" value="5.0.0-1032-azure"/>
<property name="path.separator" value=":"/>
<property name="sun.arch.data.model" value="64"/>
<property name="sun.boot.library.path" value="/usr/java/openjdk-13/lib"/>
<property name="sun.cpu.endian" value="little"/>
<property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
<property name="sun.java.command" value="end-to-end-tests-0.1.0.jar --disable-banner --reports-dir=build/reports"/>
<property name="sun.java.launcher" value="SUN_STANDARD"/>
<property name="sun.jnu.encoding" value="UTF-8"/>
<property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
<property name="user.dir" value="/home/worker/work"/>
<property name="user.home" value="/home/worker"/>
<property name="user.language" value="en"/>
<property name="user.name" value="worker"/>
<property name="user.timezone" value="Etc/UTC"/>
</properties>
<testcase name="goos.AuctionSniperEndToEndTest" classname="goos.AuctionSniperEndToEndTest" time="5.407">
<error message="The following addresses failed: 'auction:5222' failed because: java.net.UnknownHostException: auction: No address associated with hostname" type="org.jivesoftware.smack.SmackException$ConnectionException"><![CDATA[org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'auction:5222' failed because: java.net.UnknownHostException: auction: No address associated with hostname
	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:668)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:971)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:435)
	at goos.FakeAuctionServer.startSellingItem(FakeAuctionServer.kt:28)
	at goos.AuctionSniperEndToEndTest$1$1.invokeSuspend(AuctionSniperEndToEndTest.kt:14)
	at goos.AuctionSniperEndToEndTest$1$1.invoke(AuctionSniperEndToEndTest.kt)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invokeSuspend(executions.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invoke(executions.kt)
	at io.kotest.core.AsserterKt.executeWithGlobalAssertSoftlyCheck(Asserter.kt:37)
	at io.kotest.core.AsserterKt.executeWithAssertionsCheck(Asserter.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invokeSuspend(executions.kt:17)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invoke(executions.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)
	at io.kotest.core.runtime.ExecutionsKt.executeWithTimeout--MKxnPQ(executions.kt:13)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invokeSuspend(TestExecutor.kt:184)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invokeSuspend(TestExecutor.kt:179)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2$1.invokeSuspend(ExecutorExecutionContext.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.run(ExecutorExecutionContext.kt:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
]]></error>
<system-out><![CDATA[
unique-id: [engine:kotest]/[spec:goos.AuctionSniperEndToEndTest]
display-name: goos.AuctionSniperEndToEndTest
]]></system-out>
</testcase>
<testcase name="sniper joins auction until auction closes" classname="goos.AuctionSniperEndToEndTest" time="5.118">
<error message="The following addresses failed: 'auction:5222' failed because: java.net.UnknownHostException: auction: No address associated with hostname" type="org.jivesoftware.smack.SmackException$ConnectionException"><![CDATA[org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'auction:5222' failed because: java.net.UnknownHostException: auction: No address associated with hostname
	at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:668)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:971)
	at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:435)
	at goos.FakeAuctionServer.startSellingItem(FakeAuctionServer.kt:28)
	at goos.AuctionSniperEndToEndTest$1$1.invokeSuspend(AuctionSniperEndToEndTest.kt:14)
	at goos.AuctionSniperEndToEndTest$1$1.invoke(AuctionSniperEndToEndTest.kt)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invokeSuspend(executions.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2$2.invoke(executions.kt)
	at io.kotest.core.AsserterKt.executeWithGlobalAssertSoftlyCheck(Asserter.kt:37)
	at io.kotest.core.AsserterKt.executeWithAssertionsCheck(Asserter.kt:18)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invokeSuspend(executions.kt:17)
	at io.kotest.core.runtime.ExecutionsKt$executeWithTimeout$2.invoke(executions.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:102)
	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:78)
	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:31)
	at io.kotest.core.runtime.ExecutionsKt.executeWithTimeout--MKxnPQ(executions.kt:13)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invokeSuspend(TestExecutor.kt:184)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1$4.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ReplayKt.replay(replay.kt:18)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invokeSuspend(TestExecutor.kt:179)
	at io.kotest.core.runtime.TestExecutor$invokeTestCase$$inlined$invoke$lambda$1$1.invoke(TestExecutor.kt)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2$1.invokeSuspend(ExecutorExecutionContext.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at io.kotest.core.runtime.ExecutorExecutionContext$executeWithTimeoutInterruption$$inlined$suspendCoroutine$lambda$2.run(ExecutorExecutionContext.kt:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
]]></error>
<system-out><![CDATA[
unique-id: [engine:kotest]/[spec:goos.AuctionSniperEndToEndTest]/[test:sniper joins auction until auction closes]
display-name: sniper joins auction until auction closes
]]></system-out>
</testcase>
<system-out><![CDATA[
unique-id: [engine:kotest]
display-name: Kotest
]]></system-out>
</testsuite>
